zuul:
 routes:
  file-service:
   url: ${file-service}
  user-service:
   url: ${user-service}
  session-service:
    url: ${session-service}

ribbon:
  eureka:
   enabled: false

server:
 port: 8080
 
 # Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
      
spring:
  application:
    name: gateway
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
 
