# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - setup_remote_docker
      - checkout
      - run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASS
      - run: cd MetadataExtraction && ls -la && docker image build . -t metadata_service:latest && docker tag metadata_service:latest $DOCKER_USERNAME/metadata_service:latest
      - run: docker push $DOCKER_USERNAME/metadata_service:latest

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - metadata_docker
