version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - setup_remote_docker
      - checkout
      - run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASS
      - run: cd SessionService && ls -la && mvn clean install package && docker image build . -t sessionservice:latest && docker tag sessionservice:latest  $DOCKER_USERNAME/sessionservice:latest
      - run: docker push $DOCKER_USERNAME/sessionservice:latest

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - session-service-ci