version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - setup_remote_docker
      - checkout
      - run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASS
      - run: cd driveservice && ls -la && mvn clean install package && docker image build . -t driveservice:latest && docker tag driveservice:latest  $DOCKER_USERNAME/fileservice-mysql:latest
      - run: docker push $DOCKER_USERNAME/fileservice-mysql:latest

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - fileservice-ci
