# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:12.16
    steps:
      - setup_remote_docker
      - checkout
      - run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASS
      - run: cd persona-frontend && ls -la && docker image build . -t frontend_service:latest && docker tag frontend_service:latest $DOCKER_USERNAME/frontend_service:latest
      - run: docker push $DOCKER_USERNAME/frontend_service:latest

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - frontend_docker_ci
