apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
    version: "VERSION"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        version: "VERSION"
    spec:
      containers:
      - name: user-service
        image: personateam/user-service-mysql:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3333
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: DB_USERNAME
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: mysql-root-password
          value: ""
        - name: DB_HOST
          value: "mysql"
        - name: DB_NAME
          value: "userservice"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 3333
      targetPort: 3333
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-service
spec:
  rules:
  - http:
      paths:
      - path: /user
        pathType: Prefix
        backend:
          service:
            name: user-service
            port:
              number: 3333
