# Service registers under this name
# Control the InternalResourceViewResolver:
spring:
  application:
    name: user-service
    
  datasource:
        url: jdbc:mysql://localhost:3306/userservice?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
        username: root
   
  jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
 

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

    
server:
  port: 3333   # HTTP (Tomcat) port
  
  