# Service registers under this name
# Control the InternalResourceViewResolver:
spring:
  application:
    name: user-service
    
  datasource:
        url: jdbc:mysql://${DB_HOST}/${DB_NAME}?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
  
  #datasource:
      #  url: jdbc:mysql://mysql/userservice?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
       # username: testuser
        #password: 12345678
   
  jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
 

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

    
server:
  port: 3333   # HTTP (Tomcat) port
  
  
