#!/usr/bin/env groovy
pipeline {
    agent { node { label 'worker' } }

    environment {
        IMAGE_TAG = "${env.BUILD_NUMBER}"

    }

    stages {
        stage("Clone Repository") {
            steps {
               git branch: 'drive-service-jenkins', credentialsId: 'bfa23bab-8106-47fd-a41f-4c63413bfe04', url: 'https://github.com/airavata-courses/Persona'
            }
        }

        stage("Build Repository") {
            steps {
                sh "cd $WORKSPACE && mvn -f driveservice/pom.xml install -DskipTests=true"
            }
        }

        stage("Tests Repository") {
            steps {
                sh "echo test"
            }

        }

        stage("Build & Publish") {
            steps {
                sh "cd $WORKSPACE/driveservice && docker build -t personateam/driveservice:latest ."
                sh 'docker login -u personateam -p personateam'
                sh "docker push personateam/driveservice:latest"
            }

        }

        stage("Deleting local Image") {

            steps {
                sh "docker rmi personateam/driveservice:latest"
            }
        }
        
        stage("Deploy on kubernetes") {
            steps {
                sh "sed -i 's/VERSION/${env.BUILD_NUMBER}/g' $WORKSPACE/driveservice/manifest/kubernetes-manifest.yml"
                sh "cd $WORKSPACE/driveservice/manifest && kubectl apply -f kubernetes-manifest.yml"
            }
        }
    }

    post {
        always {
            sh "echo post || true"
        }

    }
}
