#!/usr/bin/env groovy
pipeline {
    triggers {
        pollSCM('* * * * *') 
    }
    agent { node { label 'worker' } }

    environment {
        IMAGE_TAG = "${env.BUILD_NUMBER}"

    }

    stages {
        stage("Clone Repository") {
            steps {
               //git branch: 'drive-service-jenkins', credentialsId: 'bfa23bab-8106-47fd-a41f-4c63413bfe04', url: 'https://github.com/airavata-courses/Persona'
                 checkout([
        $class: 'GitSCM', 
        branches: [[name: 'refs/heads/drive-service-jenkins']], 
        doGenerateSubmoduleConfigurations: false, 
        extensions: [[$class: 'CleanCheckout']], 
        submoduleCfg: [], 
        userRemoteConfigs: [[credentialsId: 'bfa23bab-8106-47fd-a41f-4c63413bfe04', url: 'https://github.com/airavata-courses/Persona']]
    ])
            }
        }

        stage("Build Repository") {
            steps {
                sh "cd $WORKSPACE && mvn -f driveservice/pom.xml install -DskipTests=true"
            }
        }

        stage("Tests Repository") {
            steps {
                sh "echo test"
            }

        }

        stage("Build & Publish") {
            steps {
                sh "cd $WORKSPACE/driveservice && docker build -t personateam/driveservice:latest ."
                sh 'docker login -u personateam -p personateam'
                sh "docker push personateam/driveservice:latest"
            }

        }

        stage("Deleting local Image") {

            steps {
                sh "docker rmi personateam/driveservice:latest"
            }
        }
        
        stage("Deploy on UI cluster") {
            steps {
                sh "sed -i 's/VERSION/${env.BUILD_NUMBER}/g' $WORKSPACE/driveservice/manifest/kubernetes-manifest.yml"
                sh "cd $WORKSPACE/driveservice/manifest && export KUBECONFIG=/home/ubuntu/.kube/config && kubectl apply -f kubernetes-manifest.yml"
            }
        }
        stage("Deploy on TACC cluster") {
            steps {
                sh "cd $WORKSPACE/driveservice/manifest && export KUBECONFIG=/home/ubuntu/.kube/tacc && kubectl apply -f kubernetes-manifest.yml"
            }
        }
    }

    post {
        always {
            sh "echo post || true"
        }

    }
}
